services:
  
  mysql:
    build: ./mysql
    container_name: ise-mysql
    restart: always
    networks:
      sql-server:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: card-game
      MYSQL_USER: ise-editor
      MYSQL_PASSWORD: ise-password

  mongo:
    build: ./mongo
    container_name: ise-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ise-editor
      MONGO_INITDB_ROOT_PASSWORD: ise-password
      MONGO_INITDB_DATABASE: card-game
    networks:
      mongo-server:

  server:
    build: ./server
    container_name: ise-server
    restart: always
    networks:
      server-nginx:
      sql-server:
      mongo-server:

  app:
    build: ./app
    container_name: ise-app
    restart: always
    networks:
      app-nginx:

  nginx:
    build: ./nginx
    container_name: ise-nginx
    restart: always
    networks:
      server-nginx:
      app-nginx:
    ports:
      - target: 443 
        published: 443
        protocol: tcp
      - target: 8443
        published: 8443
        protocol: tcp

networks:
  server-nginx:
  app-nginx:
  sql-server:
  mongo-server:
